from __future__ import annotations

from typing import Protocol


class TitanicQueryPort(Protocol):
    """타이타닉 조회 유스케이스 입력 포트."""

    def get_problem_summary(self) -> str: ...

    async def get_data(self) -> list[dict]: ...

    async def get_count(self) -> int: ...

    async def get_survived_count(self) -> int: ...

    async def get_dead_count(self) -> int: ...

    def get_model_name(self) -> str: ...

    def has_decision_tree_model(self) -> bool: ...
