"""실제 WWE 챔피언십 획득 이력 (WWE.com / 공식 방송 기준, PLE 게임 결과와 무관)."""

from __future__ import annotations

CATALOG_REVISION = 18

# (belt_name, won_at) — won_at: 실제 획득 이벤트·방송·날짜
# 키는 개인 링네임만 사용한다.
REAL_TITLE_ACQUISITIONS: dict[str, list[tuple[str, str]]] = {
    "AJ Lee": [
        ("WWE Divas Championship", "Payback — June 16, 2013"),
        ("WWE Divas Championship", "Raw — June 30, 2014"),
        ("WWE Divas Championship", "Night of Champions — September 21, 2014"),
        ("Women's Intercontinental Championship", "Elimination Chamber — February 28, 2026"),
    ],
    "AJ Styles": [
        ("WWE Championship", "SmackDown Live — September 11, 2016"),
        ("United States Championship", "Battleground — July 7, 2017"),
        ("United States Championship", "Battleground — July 25, 2017"),
        ("WWE Championship", "SmackDown — November 7, 2017"),
        ("United States Championship", "Extreme Rules — July 14, 2019"),
        ("Intercontinental Championship", "SmackDown — June 12, 2020"),
        ("Raw Tag Team Championship", "WrestleMania 37 Night 2 — April 11, 2021"),
        ("World Tag Team Championship", "SmackDown — October 20, 2025"),
        ("World Tag Team Championship", "SmackDown — December 29, 2025"),
    ],
    "Alex Shelley": [
        ("WWE Tag Team Championship", "SmackDown — October 25, 2024"),
    ],
    "Alexa Bliss": [
        ("SmackDown Women's Championship", "TLC — December 4, 2016"),
        ("SmackDown Women's Championship", "Money in the Bank — June 18, 2017"),
        ("Raw Women's Championship", "Payback — April 30, 2017"),
        ("Raw Women's Championship", "Raw — August 28, 2017"),
        ("Raw Women's Championship", "Raw — June 17, 2018"),
        ("Women's Tag Team Championship", "Raw — August 5, 2019"),
        ("Women's Tag Team Championship", "Halloween Havoc — October 25, 2020"),
        ("Women's Tag Team Championship", "Raw — July 31, 2022"),
        ("Women's Tag Team Championship", "SummerSlam — August 2, 2025"),
    ],
    "Andrade": [
        ("NXT Championship", "NXT TakeOver: Philadelphia — January 26, 2019"),
        ("United States Championship", "WrestleMania 35 — April 7, 2019"),
    ],
    "Angelo Dawkins": [
        ("NXT Tag Team Championship", "NXT TakeOver: XXV — June 1, 2019"),
        ("Raw Tag Team Championship", "WrestleMania 35 — April 7, 2019"),
        ("SmackDown Tag Team Championship", "WrestleMania 38 Night 1 — April 2, 2022"),
        ("WWE Tag Team Championship", "SmackDown — March 14, 2025"),
    ],
    "Asuka": [
        ("NXT Women's Championship", "NXT TakeOver: Dallas — April 1, 2016"),
        ("Raw Women's Championship", "WrestleMania 34 — April 8, 2018"),
        ("SmackDown Women's Championship", "TLC — December 16, 2018"),
        ("WWE Women's Championship", "Raw — May 11, 2020"),
        ("WWE Women's Championship", "SummerSlam — August 23, 2020"),
        ("Women's Tag Team Championship", "Hell in a Cell — October 6, 2019"),
        ("Women's Tag Team Championship", "WrestleMania 36 Night 1 — April 5, 2020"),
        ("Women's Tag Team Championship", "Raw — April 15, 2024"),
        ("Women's Tag Team Championship", "Raw — May 13, 2025"),
        ("Women's Tag Team Championship", "Raw — May 11, 2026"),
        ("WWE Women's Championship", "Night of Champions — May 27, 2023"),
    ],
    "Austin Theory": [
        ("United States Championship", "WrestleMania 38 Night 2 — April 3, 2022"),
        ("SmackDown Tag Team Championship", "WrestleMania XL Night 1 — April 6, 2024"),
        ("World Tag Team Championship", "Raw — March 30, 2026"),
    ],
    "Axiom": [
        ("NXT Tag Team Championship", "NXT — April 9, 2024"),
        ("NXT Tag Team Championship", "NXT No Mercy — September 1, 2024"),
    ],
    "Bayley": [
        ("NXT Women's Championship", "NXT TakeOver: Respect — October 7, 2015"),
        ("Raw Women's Championship", "Elimination Chamber — March 8, 2020"),
        ("SmackDown Women's Championship", "WrestleMania 36 Night 1 — April 5, 2020"),
        ("Women's Tag Team Championship", "Elimination Chamber — February 17, 2019"),
        ("WWE Women's Championship", "WrestleMania XL Night 1 — April 6, 2024"),
    ],
    "Becky Lynch": [
        ("SmackDown Women's Championship", "Backlash — September 11, 2016"),
        ("SmackDown Women's Championship", "Hell in a Cell — September 16, 2018"),
        ("Raw Women's Championship", "WrestleMania 35 — April 7, 2019"),
        ("SmackDown Women's Championship", "WrestleMania 35 — April 7, 2019"),
        ("SmackDown Women's Championship", "SummerSlam — August 21, 2021"),
        ("Raw Women's Championship", "SmackDown — October 22, 2021"),
        ("Women's Tag Team Championship", "Raw — February 27, 2023"),
        ("NXT Women's Championship", "Raw — September 12, 2023"),
        ("SmackDown Women's Championship", "Raw — April 22, 2024"),
        ("Women's Tag Team Championship", "WrestleMania 41 Night 1 — April 19, 2025"),
        ("Women's Intercontinental Championship", "Money in the Bank — June 7, 2025"),
        ("Women's Intercontinental Championship", "Raw on Netflix Anniversary Show — January 5, 2026"),
        ("Women's Intercontinental Championship", "WrestleMania 42 Night 1 — April 18, 2026"),
    ],
    "Bo Dallas": [
        ("WWE Tag Team Championship", "Bash in Berlin — August 31, 2024"),
        ("NXT Championship", "NXT — June 12, 2013"),
        ("Raw Tag Team Championship", "Raw — August 27, 2018"),
    ],
    "Brad Baylor": [
        ("NXT Tag Team Championship", "NXT — February 24, 2026"),
    ],
    "Brie Bella": [
        ("WWE Divas Championship", "Night of Champions — November 20, 2011"),
        ("Women's Tag Team Championship", "WrestleMania 42 Night 1 — April 18, 2026"),
    ],
    "Brock Lesnar": [
        ("WWE Championship", "King of the Ring — June 23, 2002"),
        ("WWE Championship", "WrestleMania XIX — March 30, 2003"),
        ("WWE Championship", "SummerSlam — August 17, 2014"),
        ("WWE Championship", "WrestleMania 31 — March 29, 2015"),
        ("WWE Championship", "Survivor Series — November 20, 2016"),
        ("Universal Championship", "SummerSlam — August 20, 2017"),
        ("Universal Championship", "WrestleMania 34 — April 8, 2018"),
        ("Universal Championship", "Extreme Rules — July 14, 2019"),
        ("WWE Championship", "Crown Jewel — October 31, 2019"),
        ("WWE Championship", "Day 1 — January 1, 2022"),
    ],
    "Bron Breakker": [
        ("NXT Championship", "New Year's Evil — January 4, 2022"),
        ("NXT Tag Team Championship", "NXT — February 13, 2024"),
        ("Intercontinental Championship", "SummerSlam — August 3, 2024"),
    ],
    "CM Punk": [
        ("ECW Championship", "ECW — August 27, 2007"),
        ("ECW Championship", "ECW — January 1, 2008"),
        ("World Heavyweight Championship", "Money in the Bank — July 17, 2011"),
        ("WWE Championship", "Survivor Series — November 20, 2011"),
        ("WWE Championship", "Royal Rumble — January 27, 2013"),
        ("World Heavyweight Championship", "Raw — November 25, 2013"),
        ("World Tag Team Championship", "ECW — August 4, 2008"),
        ("Intercontinental Championship", "Raw — November 8, 2024"),
        ("World Heavyweight Championship", "Saturday Night's Main Event — December 7, 2024"),
    ],
    "Charlotte Flair": [
        ("NXT Women's Championship", "NXT TakeOver: Charlotte — May 29, 2014"),
        ("WWE Divas Championship", "Night of Champions — September 20, 2015"),
        ("Raw Women's Championship", "WrestleMania 32 — April 3, 2016"),
        ("Raw Women's Championship", "SummerSlam — August 21, 2016"),
        ("Raw Women's Championship", "Hell in a Cell — October 30, 2016"),
        ("Raw Women's Championship", "Roadblock — December 18, 2016"),
        ("SmackDown Women's Championship", "SmackDown — November 14, 2017"),
        ("SmackDown Women's Championship", "SummerSlam — August 19, 2018"),
        ("SmackDown Women's Championship", "SmackDown — March 26, 2019"),
        ("SmackDown Women's Championship", "Money in the Bank — May 19, 2019"),
        ("SmackDown Women's Championship", "Super Show-Down — October 6, 2019"),
        ("NXT Women's Championship", "NXT — March 26, 2020"),
        ("Women's Tag Team Championship", "Raw — December 20, 2020"),
        ("Raw Women's Championship", "Raw — July 18, 2021"),
        ("SmackDown Women's Championship", "SmackDown — October 22, 2021"),
        ("Raw Women's Championship", "SummerSlam — August 21, 2021"),
        ("SmackDown Women's Championship", "SmackDown — December 30, 2022"),
        ("WWE Women's Championship", "WrestleMania 38 Night 2 — April 3, 2022"),
        ("Women's Tag Team Championship", "SummerSlam — August 2, 2025"),
    ],
    "Chris Sabin": [
        ("WWE Tag Team Championship", "SmackDown — October 25, 2024"),
    ],
    "Cody Rhodes": [
        ("World Tag Team Championship", "Raw — December 10, 2007"),
        ("World Tag Team Championship", "Night of Champions — June 29, 2008"),
        ("World Tag Team Championship", "Raw — August 11, 2008"),
        ("Intercontinental Championship", "SmackDown — August 12, 2011"),
        ("Intercontinental Championship", "Extreme Rules — April 29, 2012"),
        ("WWE Tag Team Championship", "Night of Champions — September 19, 2010"),
        ("Raw Tag Team Championship", "Night of Champions — September 19, 2010"),
        ("Raw Tag Team Championship", "Raw — October 14, 2013"),
        ("Raw Tag Team Championship", "Night of Champions — September 21, 2014"),
        ("Raw Tag Team Championship", "Fastlane — October 7, 2023"),
        ("SmackDown Tag Team Championship", "Fastlane — October 7, 2023"),
        ("Universal Championship", "WrestleMania XL Night 2 — April 7, 2024"),
        ("Undisputed WWE Championship", "WrestleMania XL Night 2 — April 7, 2024"),
        ("WWE Crown Jewel Championship", "Crown Jewel — November 2, 2024"),
        ("Undisputed WWE Championship", "SummerSlam — August 3, 2025"),
        ("Undisputed WWE Championship", "SmackDown — March 6, 2026"),
    ],
    "Dexter Lumis": [
        ("WWE Tag Team Championship", "Bash in Berlin — August 31, 2024"),
    ],
    "Dominik Mysterio": [
        ("NXT North American Championship", "NXT — July 18, 2023"),
        ("NXT North American Championship", "NXT — December 19, 2023"),
        ("SmackDown Tag Team Championship", "WrestleMania 39 Night 1 — April 1, 2023"),
        ("Intercontinental Championship", "WrestleMania 41 Night 2 — April 20, 2025"),
        ("Intercontinental Championship", "SummerSlam — August 2, 2025"),
    ],
    "Dragon Lee": [
        ("NXT North American Championship", "NXT No Mercy — September 30, 2023"),
        ("World Tag Team Championship", "SmackDown — October 20, 2025"),
    ],
    "Drew McIntyre": [
        ("Intercontinental Championship", "TLC — December 13, 2009"),
        ("WWE Tag Team Championship", "Night of Champions — September 19, 2010"),
        ("Raw Tag Team Championship", "Raw — September 3, 2018"),
        ("NXT Championship", "NXT TakeOver: Brooklyn III — August 19, 2017"),
        ("WWE Championship", "WrestleMania 36 Night 2 — April 5, 2020"),
        ("World Heavyweight Championship", "WrestleMania XL Night 2 — April 7, 2024"),
    ],
    "Ethan Page": [
        ("NXT Championship", "NXT Heatwave — July 7, 2024"),
        ("NXT North American Championship", "NXT — May 27, 2025"),
    ],
    "Finn Bálor": [
        ("NXT Championship", "NXT TakeOver: R Evolution — February 11, 2015"),
        ("Universal Championship", "SummerSlam — August 21, 2016"),
        ("Intercontinental Championship", "WrestleMania 34 — April 8, 2018"),
        ("United States Championship", "Raw — February 28, 2022"),
        ("Undisputed WWE Tag Team Championship", "Payback — September 2, 2023"),
        ("World Tag Team Championship", "Raw — June 24, 2024"),
    ],
    "Gunther": [
        ("Intercontinental Championship", "WrestleMania 38 Night 1 — April 2, 2022"),
        ("World Heavyweight Championship", "SummerSlam — August 3, 2024"),
        ("World Heavyweight Championship", "Raw — June 9, 2025"),
    ],
    "IYO SKY": [
        ("NXT Women's Championship", "NXT TakeOver: In Your House — June 7, 2020"),
        ("Women's Tag Team Championship", "Raw — September 12, 2022"),
        ("Women's Tag Team Championship", "WrestleMania 39 Night 2 — April 2, 2023"),
        ("WWE Women's Championship", "Night of Champions — June 17, 2023"),
        ("Women's World Championship", "Raw — March 3, 2025"),
    ],
    "JD McDonagh": [
        ("NXT Cruiserweight Championship", "Worlds Collide — January 25, 2020"),
        ("World Tag Team Championship", "Raw — June 24, 2024"),
    ],
    "Jacy Jayne": [
        ("NXT Women's Championship", "NXT — May 27, 2025"),
        ("NXT Women's Championship", "NXT — November 18, 2025"),
    ],
    "Jey Uso": [
        ("WWE Tag Team Championship", "Raw — March 3, 2014"),
        ("SmackDown Tag Team Championship", "Money in the Bank Kickoff — July 18, 2021"),
        ("Raw Tag Team Championship", "SmackDown — May 20, 2022"),
        ("Intercontinental Championship", "Raw — September 23, 2024"),
        ("World Heavyweight Championship", "WrestleMania 41 Night 2 — April 20, 2025"),
    ],
    "Jimmy Uso": [
        ("WWE Tag Team Championship", "Raw — March 3, 2014"),
        ("SmackDown Tag Team Championship", "Money in the Bank Kickoff — July 18, 2021"),
        ("Raw Tag Team Championship", "SmackDown — May 20, 2022"),
    ],
    "Joe Gacy": [
        ("WWE Tag Team Championship", "Bash in Berlin — August 31, 2024"),
    ],
    "John Cena": [
        ("United States Championship", "WrestleMania 20 — March 14, 2004"),
        ("United States Championship", "WrestleMania 25 — April 5, 2009"),
        ("United States Championship", "Night of Champions — September 19, 2010"),
        ("United States Championship", "WrestleMania 29 — April 7, 2013"),
        ("United States Championship", "WrestleMania 31 — March 29, 2015"),
        ("Intercontinental Championship", "Saturday Night's Main Event — November 8, 2025"),
        ("World Tag Team Championship", "Raw — January 29, 2006"),
        ("World Tag Team Championship", "ECW — April 1, 2007"),
        ("WWE Tag Team Championship", "SmackDown — October 3, 2010"),
        ("WWE Tag Team Championship", "Raw — April 28, 2019"),
        ("World Heavyweight Championship", "Survivor Series — November 18, 2013"),
        ("World Heavyweight Championship", "Tables, Ladders & Chairs — December 15, 2013"),
        ("World Heavyweight Championship", "Royal Rumble — January 27, 2014"),
        ("WWE Championship", "WrestleMania 21 — April 3, 2005"),
        ("WWE Championship", "Royal Rumble — January 29, 2006"),
        ("WWE Championship", "Unforgiven — September 17, 2006"),
        ("WWE Championship", "Breaking Point — September 13, 2009"),
        ("WWE Championship", "Bragging Rights — October 25, 2009"),
        ("WWE Championship", "Elimination Chamber — February 21, 2010"),
        ("WWE Championship", "WrestleMania XXVI — March 28, 2010"),
        ("WWE Championship", "Extreme Rules — May 1, 2011"),
        ("WWE Championship", "Money in the Bank — July 25, 2011"),
        ("WWE Championship", "Night of Champions — September 18, 2011"),
        ("WWE Championship", "WrestleMania 29 — April 7, 2013"),
        ("WWE Championship", "Money in the Bank — June 29, 2014"),
        ("WWE Championship", "Royal Rumble — January 29, 2017"),
        ("WWE Championship", "WrestleMania 41 Night 2 — April 20, 2025"),
    ],
    "Johnny Gargano": [
        ("NXT Tag Team Championship", "NXT TakeOver: Toronto — November 19, 2016"),
        ("WWE Tag Team Championship", "SmackDown — July 5, 2024"),
        ("WWE Tag Team Championship", "SmackDown — December 6, 2024"),
        ("NXT Championship", "NXT TakeOver: Philadelphia — January 27, 2018"),
        ("NXT North American Championship", "NXT TakeOver: New Orleans — April 7, 2018"),
    ],
    "Karrion Kross": [
        ("NXT Championship", "NXT TakeOver: XXX — August 22, 2020"),
    ],
    "LA Knight": [
        ("United States Championship", "Crown Jewel — November 4, 2023"),
    ],
    "Lash Legend": [
        ("Women's Tag Team Championship", "SmackDown — February 27, 2026"),
    ],
    "Liv Morgan": [
        ("Women's World Championship", "Money in the Bank — July 2, 2022"),
        ("Women's Tag Team Championship", "WrestleMania 39 Night 1 — April 1, 2023"),
        ("Women's Tag Team Championship", "Money in the Bank — July 1, 2023"),
        ("Women's Tag Team Championship", "WrestleMania 40 Night 1 — April 6, 2024"),
        ("Women's Tag Team Championship", "Elimination Chamber — March 1, 2025"),
        ("Women's World Championship", "King and Queen of the Ring — May 25, 2024"),
        ("WWE Crown Jewel Championship", "Crown Jewel — November 2, 2024"),
        ("Women's World Championship", "WrestleMania 42 Night 1 — April 18, 2026"),
    ],
    "Logan Paul": [
        ("United States Championship", "Crown Jewel — November 4, 2023"),
        ("World Tag Team Championship", "WrestleMania 40 Night 1 — April 6, 2024"),
    ],
    "Lyra Valkyria": [
        ("Women's Intercontinental Championship", "Raw — January 13, 2025"),
        ("Women's Tag Team Championship", "WrestleMania 41 Night 1 — April 19, 2025"),
    ],
    "Montez Ford": [
        ("NXT Tag Team Championship", "NXT TakeOver: XXV — June 1, 2019"),
        ("Raw Tag Team Championship", "WrestleMania 35 — April 7, 2019"),
        ("SmackDown Tag Team Championship", "WrestleMania 38 Night 1 — April 2, 2022"),
        ("WWE Tag Team Championship", "SmackDown — March 14, 2025"),
    ],
    "Myles Borne": [
        ("NXT North American Championship", "NXT — February 24, 2026"),
    ],
    "Naomi": [
        ("Women's World Championship", "Evolution — July 13, 2025"),
        ("Women's Tag Team Championship", "WrestleMania 38 Night 1 — April 3, 2022"),
    ],
    "Nathan Frazer": [
        ("NXT Tag Team Championship", "NXT — April 9, 2024"),
        ("NXT Tag Team Championship", "NXT No Mercy — September 1, 2024"),
        ("NXT Heritage Cup", "NXT — June 13, 2023"),
    ],
    "Nia Jax": [
        ("Women's Tag Team Championship", "SmackDown — February 27, 2026"),
        ("WWE Women's Championship", "WrestleMania 34 — April 8, 2018"),
        ("WWE Women's Championship", "Night of Champions — September 1, 2023"),
        ("Women's Tag Team Championship", "Elimination Chamber — March 1, 2025"),
        ("Women's Tag Team Championship", "WrestleMania 41 Night 1 — April 19, 2025"),
    ],
    "Oba Femi": [
        ("NXT North American Championship", "NXT — January 9, 2024"),
        ("NXT Championship", "NXT New Year's Evil — January 7, 2025"),
        ("NXT Championship", "NXT Deadline — December 6, 2025"),
    ],
    "Paige": [
        ("NXT Women's Championship", "NXT — June 20, 2013"),
        ("WWE Divas Championship", "Raw — April 7, 2014"),
        ("Women's Tag Team Championship", "WrestleMania 42 Night 1 — April 18, 2026"),
    ],
    "Penta": [
        ("Intercontinental Championship", "Raw — March 2, 2026"),
    ],
    "Randy Orton": [
        ("World Heavyweight Championship", "SummerSlam — August 15, 2004"),
        ("World Heavyweight Championship", "No Mercy — October 8, 2007"),
        ("World Heavyweight Championship", "TLC — December 15, 2013"),
        ("World Heavyweight Championship", "Battleground — October 27, 2013"),
        ("Intercontinental Championship", "Taboo Tuesday — November 9, 2004"),
        ("United States Championship", "The Great American Bash — July 23, 2006"),
        ("World Tag Team Championship", "Backlash — April 30, 2006"),
        ("World Tag Team Championship", "Raw — December 10, 2007"),
        ("Raw Tag Team Championship", "Extreme Rules — May 19, 2013"),
        ("Raw Tag Team Championship", "SmackDown — May 20, 2022"),
        ("SmackDown Tag Team Championship", "WrestleMania 34 — April 8, 2018"),
        ("WWE Championship", "No Way Out — March 1, 2009"),
        ("WWE Championship", "WrestleMania 25 — April 5, 2009"),
        ("WWE Championship", "Extreme Rules — May 3, 2010"),
        ("WWE Championship", "Night of Champions — September 21, 2014"),
        ("WWE Championship", "Hell in a Cell — October 25, 2014"),
        ("WWE Championship", "WrestleMania 33 — April 2, 2017"),
        ("WWE Championship", "Royal Rumble — January 27, 2019"),
        ("WWE Championship", "Extreme Rules — July 14, 2019"),
        ("WWE Championship", "Hell in a Cell — October 25, 2020"),
        ("WWE Championship", "Backlash — June 14, 2020"),
    ],
    "Rey Mysterio": [
        ("WWE Championship", "Raw — April 6, 2011"),
        ("World Heavyweight Championship", "WrestleMania 22 — April 2, 2006"),
        ("World Heavyweight Championship", "Fatal 4-Way — June 20, 2010"),
        ("Intercontinental Championship", "WrestleMania 25 — April 5, 2009"),
        ("Intercontinental Championship", "The Bash — June 28, 2009"),
        ("United States Championship", "Money in the Bank — May 19, 2019"),
        ("United States Championship", "Survivor Series — November 25, 2019"),
        ("United States Championship", "SummerSlam — August 11, 2023"),
        ("WWE Tag Team Championship", "No Way Out — February 18, 2004"),
        ("WWE Tag Team Championship", "WrestleMania 20 — March 14, 2004"),
        ("WWE Tag Team Championship", "SmackDown — December 12, 2008"),
        ("WWE Tag Team Championship", "SmackDown — July 21, 2009"),
        ("SmackDown Tag Team Championship", "WrestleMania 39 Night 2 — April 2, 2023"),
    ],
    "Rhea Ripley": [
        ("NXT UK Women's Championship", "NXT UK TakeOver: Blackpool — January 12, 2019"),
        ("NXT Women's Championship", "NXT TakeOver: New York — April 10, 2019"),
        ("WWE Women's Championship", "WrestleMania 37 Night 2 — April 11, 2021"),
        ("Women's Tag Team Championship", "Raw — July 18, 2021"),
        ("WWE Women's Championship", "WrestleMania 39 Night 2 — April 2, 2023"),
        ("Women's World Championship", "WrestleMania 39 Night 2 — April 2, 2023"),
        ("Women's Tag Team Championship", "Raw — January 5, 2025"),
        ("Women's World Championship", "Raw on Netflix — January 6, 2025"),
    ],
    "Ricky Smokes": [
        ("NXT Tag Team Championship", "NXT — February 24, 2026"),
    ],
    "Roman Reigns": [
        ("WWE Tag Team Championship", "Extreme Rules — October 14, 2013"),
        ("WWE Championship", "Survivor Series — November 22, 2015"),
        ("WWE Championship", "Raw — December 14, 2015"),
        ("United States Championship", "Hell in a Cell — September 25, 2016"),
        ("WWE Championship", "WrestleMania 32 — April 3, 2016"),
        ("Intercontinental Championship", "Raw — November 20, 2017"),
        ("Universal Championship", "WrestleMania 33 — April 2, 2017"),
        ("Universal Championship", "SummerSlam — August 19, 2018"),
        ("WWE Championship", "WrestleMania 38 Night 2 — April 3, 2022"),
        ("World Heavyweight Championship", "WrestleMania 42 Night 2 — April 19, 2026"),
    ],
    "Rusev": [
        ("United States Championship", "Night of Champions — September 21, 2014"),
    ],
    "Sami Zayn": [
        ("NXT Championship", "NXT TakeOver: Rival — February 11, 2015"),
        ("Intercontinental Championship", "Elimination Chamber — March 8, 2020"),
        ("Intercontinental Championship", "Clash of Champions — September 27, 2020"),
        ("Intercontinental Championship", "SmackDown — February 18, 2022"),
        ("Intercontinental Championship", "WrestleMania XL Night 1 — April 6, 2024"),
        ("United States Championship", "WrestleMania 38 Night 1 — April 2, 2022"),
        ("United States Championship", "WrestleMania 40 Night 2 — April 7, 2024"),
        ("Undisputed WWE Tag Team Championship", "WrestleMania 39 Night 1 — April 1, 2023"),
    ],
    "Seth Rollins": [
        ("NXT Championship", "NXT — July 26, 2012"),
        ("Raw Tag Team Championship", "Extreme Rules — May 19, 2013"),
        ("WWE Championship", "WrestleMania 31 — March 29, 2015"),
        ("United States Championship", "SummerSlam — August 23, 2015"),
        ("WWE Championship", "Money in the Bank — June 19, 2016"),
        ("Raw Tag Team Championship", "SummerSlam — August 20, 2017"),
        ("Raw Tag Team Championship", "Raw — December 25, 2017"),
        ("Intercontinental Championship", "WrestleMania 34 — April 8, 2018"),
        ("Intercontinental Championship", "SummerSlam — August 19, 2018"),
        ("Raw Tag Team Championship", "Raw — October 22, 2018"),
        ("Universal Championship", "WrestleMania 35 — April 7, 2019"),
        ("Raw Tag Team Championship", "SummerSlam — August 19, 2019"),
        ("Universal Championship", "SummerSlam — August 11, 2019"),
        ("Raw Tag Team Championship", "Raw — January 20, 2020"),
        ("United States Championship", "Raw — October 10, 2022"),
        ("World Heavyweight Championship", "Night of Champions — July 1, 2023"),
        ("World Heavyweight Championship", "SummerSlam Night 1 — August 2, 2025"),
        ("WWE Crown Jewel Championship", "Crown Jewel — October 11, 2025"),
    ],
    "Sol Ruca": [
        ("Women's Intercontinental Championship", "Clash in Italy — May 31, 2026"),
    ],
    "Solo Sikoa": [
        ("NXT North American Championship", "NXT 2.0 — September 13, 2022"),
        ("United States Championship", "WrestleMania 39 Night 2 — April 2, 2023"),
    ],
    "Stephanie Vaquer": [
        ("NXT Women's North American Championship", "NXT Vengeance Day — February 15, 2025"),
        ("NXT Women's Championship", "NXT Roadblock — March 11, 2025"),
        ("Women's World Championship", "Wrestlepalooza — September 20, 2025"),
    ],
    "The Miz": [
        ("WWE Championship", "WrestleMania 27 — April 3, 2011"),
        ("WWE Championship", "Money in the Bank — July 17, 2011"),
        ("Intercontinental Championship", "WrestleMania 25 — April 5, 2009"),
        ("Intercontinental Championship", "Extreme Rules — June 4, 2012"),
        ("Intercontinental Championship", "Raw — April 11, 2016"),
        ("Intercontinental Championship", "SmackDown — August 23, 2016"),
        ("Intercontinental Championship", "Raw — November 22, 2016"),
        ("Intercontinental Championship", "Raw — June 4, 2018"),
        ("Intercontinental Championship", "Elimination Chamber — February 17, 2019"),
        ("Intercontinental Championship", "WrestleMania 39 Night 2 — April 2, 2023"),
        ("United States Championship", "WrestleMania 27 — April 3, 2011"),
        ("United States Championship", "WrestleMania 32 — April 3, 2016"),
        ("Raw Tag Team Championship", "Raw — April 19, 2016"),
        ("Raw Tag Team Championship", "Raw — December 4, 2016"),
        ("Raw Tag Team Championship", "Raw — January 22, 2018"),
        ("Raw Tag Team Championship", "Raw — April 15, 2019"),
        ("Raw Tag Team Championship", "Raw — February 14, 2020"),
        ("SmackDown Tag Team Championship", "SmackDown — February 12, 2021"),
        ("SmackDown Tag Team Championship", "WrestleMania 38 Night 1 — April 2, 2022"),
        ("World Tag Team Championship", "WrestleMania 27 — April 3, 2011"),
        ("World Tag Team Championship", "WrestleMania 40 Night 1 — April 6, 2024"),
    ],
    "Tiffany Stratton": [
        ("NXT Women's Championship", "NXT Battleground — May 28, 2023"),
        ("WWE Women's Championship", "Saturday Night's Main Event — December 6, 2025"),
        ("Women's United States Championship", "SmackDown — April 24, 2026"),
    ],
    "Tommaso Ciampa": [
        ("NXT Tag Team Championship", "NXT TakeOver: Toronto — November 19, 2016"),
        ("WWE Tag Team Championship", "SmackDown — July 5, 2024"),
        ("WWE Tag Team Championship", "SmackDown — December 6, 2024"),
        ("NXT Championship", "NXT — July 18, 2018"),
    ],
    "Tony D'Angelo": [
        ("NXT North American Championship", "NXT Stand & Deliver — April 1, 2023"),
        ("NXT Tag Team Championship", "NXT The Great American Bash — July 30, 2023"),
        ("NXT Championship", "NXT Stand & Deliver — April 4, 2026"),
    ],
    "Trick Williams": [
        ("NXT North American Championship", "NXT No Mercy — September 30, 2023"),
        ("NXT Championship", "NXT Stand & Deliver — April 7, 2024"),
        ("NXT Championship", "NXT — October 1, 2024"),
        ("United States Championship", "WrestleMania 42 Night 2 — April 19, 2026"),
    ],
}


def individual_title_acquisitions() -> dict[str, list[tuple[str, str]]]:
    """개인 링네임 기준 획득 이력."""
    return {name: list(reigns) for name, reigns in REAL_TITLE_ACQUISITIONS.items() if reigns}
